### ISSUE TITLE
Problems with namespace.

### ISSUE THREAD

**Issue by eugeniomichetti** [dcarbone/xml-writer-plus#1]
When I call the appenedHash(array $values) this method returns a XML invalid.

My array:

```php
$hash = array(
            'tem:usuarioCliente' => '1234',
            'tem:senhaCliente' => '123',
            'tem:codigoAgencia' => '123',
        );
```

Return:

```xml
<tem:usuarioCliente xmlns:tem="Diego"/>
<tem:senhaCliente xmlns:tem="123456"/>
<tem:codigoAgencia xmlns:tem="1000"/>
```

Debugging the code you see this:
```php
public function writeElementNS($prefix, $name, $uri = null, $content = null)
    {
        list($prefix, $uri) = $this->resolveNamespace($prefix, $uri);
        return parent::writeElementNS($prefix, $name, $uri, $content);
    }
```
And when this method is called, always is sended $prefix, $name, $content,$uri, causing the problem.

**Comment by dcarbone** [comment]
Yep, i see the issue.  Thanks for reporting this, i'll get it fixed asap.  Will also add a test around it.

**Comment by dcarbone** [comment]
@eugeniomichetti: I have pushed a new tag 0.5.1 that should resolve this issue.  Let me know if you see any others!

**Comment by dcarbone** [comment]
@eugeniomichetti: can this issue be closed?

**Comment by eugeniomichetti** [comment]
Yes, the problem is resolved.
