### ISSUE TITLE
XMLWriter::flush(): Invalid or uninitialized

### ISSUE THREAD

**Issue by ekavando** [dcarbone/xml-writer-plus#2]
When I tested it with php 7.4.13 version it gave this error
XMLWriter::flush(): Invalid or uninitialized XMLWriter object in XMLWriterPlus.php on line 43

**Comment by dcarbone** [comment]
@eka7a: Could you provide a code snippet around what you tried?

**Comment by dcarbone** [comment]
I have removed the destructor entirely as it really shouldn't be necessary.
